---
- name: Установка nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: yes

- name: Копирование основного конфига nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Перезапустить nginx
  become: yes

- name: Копирование конфига для default сайта
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: '0644'
  notify: Перезапустить nginx
  become: yes

- name: Убедиться, что сайт default включён
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: Перезапустить nginx
  become: yes

- name: Включить и запустить nginx
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes
