---
- name: Развертывание приложения с установкой Docker через роль
  hosts: app
  become: yes
  roles:
    - docker

  tasks:
    - name: Клонирование репозитория приложения Django
      git:
        repo: "https://github.com/mdn/django-locallibrary-tutorial.git"
        dest: /home/vagrant/django-locallibrary-tutorial
        version: main

    - name: Загрузка Docker-образа с приложением
      docker_image:
        name: timurbabs/django
        source: pull

    - name: Запуск контейнера с приложением
      docker_container:
        name: django_app
        image: timurbabs/django
        state: started
        ports:
          - "8000:8000"

