---
- name: Развертывание приложения Django
  hosts: app
  become: yes
  tasks:
    - name: Клонирование репозитория приложения
      git:
        repo: https://github.com/mdn/django-locallibrary-tutorial.git
        dest: /home/vagrant/django-locallibrary-tutorial
        version: main

    - name: Загрузка Docker-образа приложения
      docker_image:
        name: timurbabs/django
        source: pull

    - name: Запуск контейнера с приложением
      docker_container:
        name: django_app
        image: timurbabs/django
        state: started
        ports:
          - "8000:8000"
