# Vagrantfile

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Количество требуемых машин
  SERVERS = 3

  # Указываем имя сетевого интерфейса под Windows, если нужно бриджиться:
  BRIDGE = "Intel(R) Wi-Fi 6 AX201 160MHz"

  def create_host(config, hostname, ip)
    config.vm.define hostname do |host|
      # Приватная сеть с ip
      host.vm.network "private_network", ip: ip

      # Если нужно, чтобы ВМ получили адрес во внешней сети (бридж):
      host.vm.network "public_network", bridge: BRIDGE

      host.vm.hostname = hostname

      # Устанавливаем Python3 и включаем автоматическую синхронизацию времени
      host.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y python3 python3-apt
        sudo timedatectl set-ntp true
      SHELL
    end
  end

  (1..SERVERS).each do |machine_id|
    create_host(config, "srv#{machine_id}", "192.168.56.#{200 + machine_id}")
  end
end
