---
- name: Развертывание приложения Django через Docker
  hosts: app
  become: true
  
  roles:
    - docker  # Вызов роли для установки Docker

  tasks:
    - name: Клонирование репозитория приложения (опционально)
      git:
        repo: https://github.com/mdn/django-locallibrary-tutorial.git
        dest: /home/vagrant/django-locallibrary-tutorial
        version: main

    - name: Загрузка Docker-образа приложения
      docker_image:
        name: timurbabs/django
        source: pull

    - name: Запуск контейнера с приложением Django
      docker_container:
        name: django_app
        image: timurbabs/django
        state: started
        restart_policy: always
        published_ports:
          - "8000:8000"

