---
- name: Установка и настройка nginx на группе web
  hosts: web
  become: true
  roles:
    - role: nginx
      vars:
        django_upstream_host: 192.168.56.202  # IP одного из app-серверов
        django_upstream_port: 8000

