---
roles:
  - name: docker
    src: https://gitlab.com/ansible-roles6370612/docker.git
    scm: git
    version: main

  - name: nginx
    src: https://gitlab.com/ansible-roles6370612/ansible-role-nginx.git
    scm: git
    version: main

